# Generated by Django 4.1.2 on 2022-11-15 06:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_profile_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileSetting',
        ),
    ]
